FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json tsconfig.json ./

RUN npm install

COPY /apps ./apps
COPY /packages ./packages

# Custom Scripts in global package.json
RUN npm run db:generate

RUN npm run build

EXPOSE 3000

ENTRYPOINT ["npm", "run", "start-user-app"]