'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
import { usePathname } from 'next/navigation';

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: {
    // absolute: "Absolute Title",
    default: "Default Title",
    template: "%s | App",
  },
  description: "Generated by create next app",
};

const navLinks = [
  { href: '/blog', label: 'Blog' },
  { href: '/product', label: 'Products' },
  { href: '/dashboard', label: 'Dashboard' },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const isActive = (href: string) => pathname === href;
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ul>
            {navLinks.map(({ href, label }) => (
              <li key={href}>
                <Link href={href} className={isActive(href) ? 'font-bold underline' : ''}>
                  <p>{label}</p>
                </Link>
              </li>
            ))}
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
